import "../globals.css";
import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import { cn } from "@/lib/utils";
import { ModalProvider } from "./admin/_components/Modal/ModalContext";

const fontSans = FontSans({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="">
      <ModalProvider>
        <body className={cn("min-h-screen antialiased ", fontSans.className)}>
          {children}
          <div id="modal-root" />
        </body>
      </ModalProvider>
    </html>
  );
}
